# version: '3'
services:
  nxtech-be:
    container_name: nxtech-be
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8010:80'
    volumes:
      - .:/app
    networks:
      - dev_host


networks:
  dev_host:
    driver: bridge
    external: true


